不具合修正（actions/download-artifact@v4の出力先であるpathを指定する）
＜修正対象のGitHub Actions エラー＞
Run aws s3 sync dist/ s3://s-0001.reflet.jp/

The user-provided path dist/ does not exist.
Error: Process completed with exit code 255.

以上